<a href="https://colab.research.google.com/github/Fatma-Chaouech/PyTorch-Learning-Journey/blob/main/Intermediate_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Tensors

In PyTorch, if a torch method ends with an underscore, it means that it directly affects the value of the passed variable, like inplace=True.

We could also specify a variable that will contain the resulting value using the argument "out". The variable specified in "out" will be the exact same object as the variable that we affected the result to. Let's see a quick example :

In [3]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c), old_id    # make sure that our new c is the same object as the old one

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.2058, 0.1343],
        [1.1684, 1.1062]])


Variable assigning in PyTorch doesn't generate a copy. If you want a separate copy of the data to work on, you should use the clone() method. 

In [6]:
# simple assigning
v = torch.ones(2, 2)
u = v

v[0][1] = 561  # we change a...
print(v)       # ...and b is also altered


# using clone()
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[  1., 561.],
        [  1.,   1.]])
tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


**It's important to note that if your source tensor has autograd, enabled then so will the clone.** If you want to turn off the autograd, use the detach() method before cloning.

# GPU Computing

We first need to check if we have a GPU available with .is_available() method.

In [2]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

We have a GPU!


The CPU does computation on data in the computer's RAM. However, **the GPU has dedicated memory attached to it.** Thus, we should move all the data needed for that computation to memory accessible by the GPU. We often say that we "move the data to the GPU".